---
name: Build and Push Website Builder Docker Image to Google Cloud Platform
on:
  push:
    branches: [ main ]        
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ github.event.inputs.choice }}
      IMAGE_NAME: website-builder
      PROJECT_ID: teachmint-dev
      LOCATION: asia-south1
      ARTIFACTORY: pac-docker-artifact-registry

    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: check
      run: echo "hello peter"
